# SPDX-FileCopyrightText: Copyright (c) 2020-2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
title: ICCQ.ru
email: yegor256@gmail.com
description: >
  International Conference on Code Quality (ICCQ)
baseurl: ""
url: "https://www.iccq.ru"
markdown: kramdown
author:
  name: "Yegor Bugayenko"
  email: yegor256@gmail.com
breadcrumbs:
  - /2021.html: 2021
  - /2022.html: 2022
  - /2023.html: 2023
  - /2024.html: 2024
  - /2025.html: 2025
  - /2026.html: 2026
encoding: utf-8
timezone: Europe/Moscow
permalink: :year-:month-:day-:title.html
exclude:
  - README.md
  - Gemfile.lock
  - Gemfile
  - LICENSE.txt
  - proceedings
  - cfp
  - ads

plugins:
  - jekyll-feed
  - jekyll-redirect-from

feed:
  title: www.iccq.ru
  subtitle: International Conference on Code Quality
  path: rss.xml

sass:
  style: compressed
  deploy_style: compressed
  compile_in_place: false
